# Generated by Django 5.2.5 on 2025-08-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lessons_completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lessons_started',
        ),
    ]
