# Generated by Django 5.2.5 on 2025-09-04 07:19

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lessonsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='sections_completed',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
