# Generated by Django 5.2.5 on 2025-09-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lesson_slug_userlessonprogress_sections_completed'),
    ]

    operations = [
    ]
